### PR TITLE
feat: Add new interactive deploy workflow

### PR DESCRIPTION
**Pull request by icaraps**
* with npm install caching
* with cached build
* with incremental build

### CODE REVIEW

**Comment by icaraps** [comment]
Tested it here https://github.com/AdobeDocs/project-firefly-page/actions/workflows/deploy.yml

**Review by shazron — APPROVED** [review]

**Comment by icaraps** [comment]
Thanks for merging ! Added some docs here https://github.com/adobe/gatsby-theme-aio#using-interactive-workflow

**Comment by icaraps** [comment]
@shazron `actions/cache@v1` can be updated to `actions/cache@v2` now

**Comment by shazron** [comment]
> @shazron `actions/cache@v1` can be updated to `actions/cache@v2` now

this PR good? (untested) https://github.com/adobe/aio-cli-plugin-doc/pull/13

**Pull request merged**
